# Generated by Django 6.0.5 on 2026-05-26 08:39

import questions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=questions.models.profile_avatar_upload_to, verbose_name='аватар'),
        ),
    ]
